CREATE TABLE IF NOT EXISTS sales_orders (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  book_id INT NOT NULL,
  customer_name VARCHAR(160) NOT NULL,
  quantity INT NOT NULL,
  unit_sell_price DECIMAL(10, 2) NOT NULL,
  discount DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
  total_amount DECIMAL(10, 2) NOT NULL,
  ordered_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_sales_orders_book
    FOREIGN KEY (book_id) REFERENCES books(id)
    ON DELETE RESTRICT
);
